project:
  type: website
  output-dir: docs

website:
  title: "Noterat"
  navbar:
    right:
      - about.qmd
      - ideas.qmd
      - now.qmd
format:
  html:
    theme: cosmo
    css: styles.css



