---
title: "The differentiated self"
author: ""
date: "2024-02-16"
categories: [leadership, management]
bibliography: references.bib
draft: true
id: "202302161955"
---

Right now at work I am taking a leadership course. It's based on the work of Gevais Bushe that he has named "Clear Leadership". At the same time I was recommended the book "7 rules of power" by Jeffry Pfeffer.

The books are very different and they talk about different aspects of social interaction in the workplace. Bushe starts from the fact that...

I think I have to go back to the drawing board.

I don't have any good notes from the books.

I really liked Clear Leadership and disliked 7 rules of power.

In this text I am trying to build a framework based on both books since I believe there is a lot to be learned from both of them.

# Clear Leadership

## Interpersonal mush

Bushe defines a term: interpersonal mush.

Bushe believes that sense making is key to understanding a lot of the dynamics that takes place in the working environment.

# 7 rules of power

What are the books about, actually.

I don't think they are trying to solve the same problem. The authors are trying to solve different problems. And they have different approach to different problems.

What are the books trying to solve and why?

Why do I want to compare them?

I am reading a course in leadership at work. I really like the literature that was given ahead of the course.

It's a book by G. Bushe named "Clear leadership".

[@bushe2010]