---
title: 'Klar kommunikation - börja varje mening med "jag"'
date: "2024-02-20"
categories: [ledarskap, TIL]
draft: true
id: "202402202033"
---

Jag var på en ledarskapskurs som bygger på konceptet "Klart ledarskap". Ett konkret verktyg som jag fick med mig var att kommunicera i "jag-form". Alltså att jag ska prata och skriva allt på formen som utgår från mig själv.

Under kursen fick vi göra en övning där vi berättade om en situation. Första versionen hade en fri berättarteknik, den andra gången skulle vi beskriva den i "jag-form". Alltså att VARJE MENING skulle börja med "jag".

Naturligtvis blev detta stolpigt och inget som jag kommer applicera så bokstavligt.

Men.

Det blev en väldigt skillnad i vad man säger. Man fick väga sina ord på guldvåg eftersom jag kände ett mycket större ansvar att uttrycka mig på ett korrekt sätt. Det rådde inga tvivel om att det är jag som sagt detta. Jämför detta med hur man använder uttryck som "vi", "man", "dom" osv. Där är det inte alls lika tydligt vem som är avsändaren.

Dessutom är det svårt för mig att uppriktigt säga att "vi" eller "dom" tycker detta. Ska jag föra talan för någon på ett medvetet sätt försöker jag verkligen förstå vad den gruppen/personen tänker/känner.

Detta var dock obekvämt eftersom jag är uppväxt med att man inte ska fokusera så mycket på sig själv. Jag ska inte ta över samtal. Men jag märker hur detta snarare skapar en tydlighet i var jag står och det gör det lättare för omgivningen att förhålla sig till mig.

Det kan till och med utmana vilket gör att man kan ha en bra diskussion om sina oenigheter.