---
title: 'Reflektion av boken "Risk - a short introduction"'
author: ""
date: 2024-03-27
categories:
  - beslutsfattande
  - risk
draft: true
id: "202403272046"
bibliography: references.bib
---

Det verkar som att dom flesta experter överskattar sin förmåga att lägga prognoser.

Borde inte många av våra processer egentligen bottna i att man ska kommunicera risk till allämenheten så att dom kan delta. Om vi tar detaljplaneprocessen som exempel. Där borde samrådet och granskningen vara en plats där kommunen kan kommunicera vilka risker som finns med en utbyggnad. Då har medborgarna möjlighet att delta i bedömningen av risken som det kollektiva ska ta.

På det sättet så uppskattar jag verkligen demokrati och hur vårat samhäller fungerar. Det finns möjlighet att delta i utformningen av staden.

Att fatta goda beslut handlar om att lära sig risk hantering. Alltså att betrakta alla utfall som kan påverka negativt. Detta betyder inte att beslutet blir lättare, tvärt om, det kan det bli svårare.

Jag tycker att försikghetprincipen är ett bra förhållningssätt när man har att göra med handlingar som kan få katastrofala följder. Man använder detta inom miljörätten. Jag tycker det är ett bra sätt att resonera.

> Decision theory looks at choices from three complementary perspectives. One is logical, or normative, analysis, identifying the choices that we would make, if we were fully informed, if we were fully in touch with our values, and if we followed consistent rules, however hard our choices are. Those are, of course, big ‘ifs’. The second decision theory perspective is the descriptive study of the necessarily imperfect ways in which people actually make choices. The third perspective involves prescriptive interventions, trying to bridge the gap between the normative ideal and the descriptive reality. Thus, decision theory asks the questions that decision-makers ask themselves: What decision am I facing? How well am I facing it? How could I do better?

@fischhoff2011

Bra för mig att få en mer konkret introduktion i vad man menar med normativa, descriptiva och prescriptiva perspektiv. Jag har ofta hört dom i andra sammanhang men inte riktigt förstått vad man menar.

Så den första tittar mer på vad som är "rätt beslut". Man utgår från att man har fullständig information och att man kan fatta ett perfekt beslut.

Herbert Simon har olika sätt att förenkla beslutsfattande:

1.  Approximerad optimering - man avgränsar problemet så att det går att hantera.
2.  Satisficiera - man avgränsar inte, men man söker inte efter den optimala lösningen.

Jag brukar nog kalla alternativ 2 för "good enough lösningar". Jag tycker dom är tillräckligt bra.

Risker hotar saker som vi värderar. Detta är en bra definition av risk.

Vi är mer villiga att ta på oss risk om det sker frivilligt:

> Starr proposed that people accept greater risk from general aviation because they assume it voluntarily, when they decide to travel in private planes; in contrast, the risks of commercial aviation are involuntary, for people who must Uy that way.