---
title: 'Reflektion av boken "Smart choices"'
author: ""
date: 2024-03-24
categories:
  - beslutsfattande
draft: true
id: "202403241917"
---

Detta är en kort reflekterande text om boken "Smart choices" av Hammond, Keeney och Raiffa.

Författarna presenterar en beslutsprocess som förkortas PROACT som står för:

-   ***Pr***oblem

-   ***O***bjectives

-   ***A***lternatives

-   ***C***onsequences

-   ***T***radeoffs

Jag har omedvetet använt mig alla delar. Detta har gjorts på ett ostrukturerat sätt. Med denna process kan jag lättare orientera mig bland dom olika stegen när jag fattar ett beslut.

Just att kunna orientera mig i processen är viktigt för mig. Då kan jag på ett medvetet sätt röra mig mellan olika skeden ifall jag ser att det behövs. Om jag t.ex. inte känner mig nöjd, då kanske det bottnar i att jag har för få alternativ och då kan jag gå tillbaka till den delen i PRO**A**CT.

Med PROACT kan jag även se det som en iterativ process. Jag kör igenom PROACT på 10 minuter för att se var jag landar. Sen ger jag mig själv mer tid och kan utforska dom olika skeden djupare.

Jag kommer ta med mig att man kan skilja på utfallet och beslutsprocessen. Bryta ut utfallet till en process som har en slumpmässig komponent. Alltså att det är inte säkert att man får önskat utfall, detta är en process för att öka sannolikheten att man får önskat utfall. Jag gillar det eftersom jag har en grundläggande syn på världen som bottnar i slump. Få saker går att säga med fullständig säkerhet.

Att ställa frågan "varför" tycker jag är ett väldigt bra verktyg för att gräva djupare i ens tankar och känslor kring olika saker. Jag gillar också att författarna lägger fokus på att man ska blicka in i sig själv för att särskåda sina sina mål.

Det blir ett sätt att stå stadigt i sig själv, ett grundat beslut i sin egen uppfattning av sitt inre. Det ger ett väldigt ägande och känsla av ansvar.

Jag gillar också att boken arbetar mycket med problemdefinitionen. Att man ska vara kreativ där. Detta är något som jag märker är svårt. Det är väldigt lätt att direkt gå på mål, alternativ m.m. Eller till och med direkt gå på lösningar, utan att arbeta igenom problemformuleringen.