---
title: 'Tankar om boken "Bestäm dig!"'
author: ""
date: 2024-02-24
categories:
  - beslutfattande
draft: true
id: "202402240839"
---

# Bestäm dig!
Nedan är en kort reflekterande text om boken "Bestäm dig" av Pelle Tornell.
## Förnuft och magkänsla – ett motsatspar
Boken tar avstamp Tornell:s motsatsbegreppen förnuft och magkänsla.  Jag tycker begreppen påminner om tankar och känslor. Förnuftet manifesteras som tankar och magkänslan som känslor. Min upplevelse är att tankar och känslor har en tendens att flyta ihop. Ofta driver dom  varandra. Detta gör det svårt att orientera sig i vad som är tankar och känslor, och därför också förnuft och magkänsla. Jag undrar om det är detta fenomen som föder flera beslutsfällor.

Överlag tycker jag att Tornell slår ett slag för magkänslan. Min tolkning av Tornell är att han tycker att känslor spelar en viktig roll vid beslutsfattande. Detta gäller även i en professionell miljö. Känslorna kan förmedla information som är för komplex för förnuftet att ta till sig.
## Hur jag förhåller mig till tankar och känslor
Jag är väldigt kluven till Tornell:s förhållningssätt. Jag har fram till rätt nyligen inte accepterat "magkänslan" som en godtagbart skäl till att fatta ett beslut. Jag har tidigare tänkt att den känslan behöver beskrivas och rationaliseras för att jag ska kunna acceptera den. 

Det finns en plats för att beskriva och rationalisera. Dock finns det en risk med att tankarna som används för att beskriva och rationalisera känslan gör att jag tappar bort den ursprungliga känslan. Jag tror att Tornell skulle säga att jag tappar bort min magkänsla, som är en viktig aspekt i beslutsfattandet, precis som förnuftet. 
## Beslutsfällor
Tornell fortsätter med att beskriva olika beslutsfällor. Alltså vanliga fel som gör att man fattar ett felaktigt beslut.

Min favorit är hybrisfällan eftersom jag tycker den ofta uppstår i samband med olika projekt. Att man på grund av okunskap överskattar sin egen förmåga. Sen står man där, med en halv västlänk och en övertrasserad budget.

Inramningsfällan är också en favorit. Jag såg en mamma berätta för sina barn med en väldig inlevelse att de minsann också äntligen skulle få lämna lekplatsen så att de fick komma hem. Alla barnen blev överlyckliga över denna nyhet. Den mamman ramade informationen som ett riktigt proffs – hatten av.
