---
title: "Upplevelsekuben och dess användningsområden"
author: ""
date: "2024-02-22"
categories: [ledarskap, TIL, klart-ledarskap]
draft: true
id: "202402222000"
---

Efter att några övningar med upplevelsekuben börjar jag förstå dess styrka. Kort går upplevelsekuben ut på att analysera sin upplevelse utifrån följande kategorier:

-   Observationer

-   Tankar

-   Känslor

-   Viljor

Till en början tyckte jag att det var svårt att skilja på exempelvis tankar och känslor. Eftersom dom driver varandra tyckte jag att det var svårt att stanna och beskriva. Jag hann inte med min egen tanke och känsloloop.

Efter att man fick vänja sig vid övningen fick vi använda den i en situation där en person skulle vara för "intim". Alltså när någon exempelvis häver ur sig uppleverlser helt oreflekterat. Personen dumpar över allt på motparten. Motparten kan lätt bli överbelastad i en sådan situation och det blir svårt att orientera sig i samtalet och i sin egen upplevelse.

Det slog mig när jag provade på att "dumpa" så kan jag lättare styra samtalet och om det görs medvetet med den avsikten skulle jag säga att det blir en en härskarteknik.

Det intressanta är att upplevelsekuben blir ett sätt att metodiskt reda allt som dumpas över en. Det kan vara så enkelt att man rent konkret säger: "*Stop, nu blir detta samtal lite rörigt, jag måste reda ut. Jag tänker att ..., känner att .., observerar att ..., vill att ...*".

I dom allra flesta fall tror jag att det kommer räcka för att kunna ha en mer konstruktivt samtal. Har man riktigt otur och träffar på någon som använder detta medvetet så kommer nog personen inte att acceptera när man vill stoppa samtalet.

Jag ser också hur det finns en risk med att använda dessa verktyg utan det nyfikna självet. Det kan lätt bli att man själv använder härskartekniker mot andra.