---
title: "Köra simuleringar av Mike+ utifrån väderradarfiler"
date: 2024-05-20
categories: [modeling]
draft: true
id: 202405201522
---

# Simulera spill- och dagvattensystem med faktiska regn

Syftet med detta projekt är att utreda ifall det är teknisk möjligt att producera regnfiler för Mike+ by DHI utifrån väderradar. Frågan är vad jag vill - om jag vill göra det själv eller definiera detta som ett examensarbete. Det är bättre att definiera detta som ett examensarbete. Samtidigt är det inte fel att utreda befintlig teknik för att förstå hur detta skulle kunna fungera i framtiden.

## Potentiellt värde - modellerna simulerar verkliga händelser och simulerade regn

Det värde som jag tror vi kan fånga är att om vi kör dag- och spillvattenmodeller (modeller) utifrån faktiskt väderradar är följande:

-   Extrema väderhändelser har ofta mycket data i form av mätningar, kort m.m. Detta gör att modellen då går att stämma av mot verkligheten.

-   Man kan identifiera olika väderscenarion som skapar problem i olika områden och då förstå hur dessa kan hanteras.

Ett problem som man stöter på idag är att analysen blir för svår - alltså att en körning visar att allt är översvämmat, men man har svårt att urskilja var exakt "flaskhalsen" befinner sig.

Detta kanske skulle bli lättare att identifiera om man körde många olika regnhändelser
